### ISSUE TITLE
Specifying encoding 

### ISSUE THREAD

**Issue by dachafra** [kg-construct/rml-target-source-spec#1]
issue:  not possible to specify source encoding

suggestion: add support for describing source encoding. With the focus on text based sources it is important to be able specify the encoding of input sources.

**Comment by dachafra** [comment]
Issue transferred to the correct repo ;-)

**Comment by DylanVanAssche** [comment]
Extended the scope to Targets & Sources instead of sources only.

**Comment by DylanVanAssche** [comment]
No objections to my proposal here: https://github.com/kg-construct/rml-target-source-spec/issues/1#issuecomment-1063749416
I will put it like this in the v0.1
