### ISSUE TITLE
Why keep a separate DataIO spec?

### ISSUE THREAD

**Issue by frmichel** [kg-construct/rml-target-source-spec#12]
As I'm reading the target spec I'm wondering where is the definition of rmlt:LogicalTarget and associated properties.

As a reader I'd expect to have a self-contained spec that includes everything.

**Comment by andimou** [comment]
I think that the `rmlt:LogicalTarget` should be defined in this spec but the concrete data descriptions are beyond the RML spec and that's why in the past we suggested to have it as a separate spec.

**Comment by andimou** [comment]
after discussions during the call: we need @DylanVanAssche to clarify what's going on.

Source/Target should describe the RML vocab and Data IO the descriptions of the data with other vocabs but the specs currently seem to be different.

**Comment by DylanVanAssche** [comment]
I agree with @frmichel 

Separating the specs had some benefits, but it becomes a mess now with refactoring everything regarding RML Core, etc.
I would prefer to have 1 spec but keeping the DataIO and RML glue in the spec in separate chapters of the spec, so the DataIO part can still be re-used if needed. Will make a proposal.
