### ISSUE TITLE
No constraint on what a target should be => need to say this is implementation-dependent?

### ISSUE THREAD

**Issue by frmichel** [kg-construct/rml-target-source-spec#13]
In the examples, the target may be a VOID data or a DCAT dataset. Yet there is no constraint here.
So how should a processor know whether the target is given by void:dataDump or dcat:downloadURL or anything else?

If this is implementation-dependent, then it should be stated explicitly.

**Comment by DylanVanAssche** [comment]
I agree that a set of default descriptions would be good, but keeping it open as well.
Will make a proposal.
