### ISSUE TITLE
base Vs view

### ISSUE THREAD

**Issue by andimou** [kg-construct/rml-target-source-spec#5]
The current RML spec says

> A logical source can be one of the following:

>   A base source (any input source or base table),
>    a view (in case of databases)

should that remain as it is?

**Comment by DylanVanAssche** [comment]
Do we need to handle this in our spec actually?
If you can specify SQL queries, you can leverage SQL VIEWS though?

**Comment by andimou** [comment]
I think it might be good, I see the merit off what @pmaria suggests as well but we have to become more concrete. 

Would base imply that the Logical Source corresponds to the whole Data source and if the Logical Source is part of the Data Source then it's a view?  question is, would that make a difference?

**Comment by DylanVanAssche** [comment]
> However, I think the core spec should be able to speak solely about logical sources. And there can be a separate section, or spec for implementation on relational databases which describes how a logical source can be implemented in terms of basetables and or views etc..

I agree with this.
Moreover, I found the distinction between base and view a bit weird in the spec. I'm probably too young to know its history :) 
How it is currently proposed:

- Logical Source
  - rml:source : describe how to access the source (rml:Source)
  - rml:referenceFormulation : describe how to refer to data elements in the source
  - rml:iterator : describe the iteration, if applicable 

- Source
  - rml:access : actual access description, external ontologies
  - rml:encoding : encoding format of the data, see #1 
  - rml:compression : compression format of the data, see #9   

There's currently a gap for RDBs: specifying SQL queries is not possible (like `rml:query`)
`rr:tableName` & `rr:column` are supported, but not views of course.
If we have something like `rml:query` you have more flexibility and have view support for free.

**Comment by bjdmeest** [comment]
I agree with Pano and Dylan. I would put this at the discretion of `rml:access` (i.e., specific per data source): in RDB you can fetch a table or a specific query, in RDF you can fetch the graph or do a SELECT or a CONSTRUCT, who knows what you can do in other sources, but in the end, you just have 'results' that can be iterated on. And so the whole discussion of "base vs view" can be kept out of RML core (and can be specified per data source type)
