### ISSUE TITLE
Specify how empty literals look like

### ISSUE THREAD

**Issue by DylanVanAssche** [kg-construct/rml-target-source-spec#6]
We should be able to specify how a data source specifies empty literals:

- Text: `"NULL"`, `""`, ``, `"random word"`
- Special value: `null` in JSON for example
- ...

Is a job for the DataIO spec: https://rml.io/specs/dataio/

Split of https://github.com/kg-construct/rml-fno-spec/issues/16

**Comment by DylanVanAssche** [comment]
Add a property to specify null values like `csvw:null`:

```
rml:logicalSource [
  rml:source "/my/data/file.csv";
  rml:null "";
  rml:null "NULL";
]
```

You can specify zero, one or multiple NULL values for any kind of source or target (CSV, JSON, etc.).
If not specified, all values are considered valid? Or should we have a default?

**Comment by DylanVanAssche** [comment]
@pmaria Isn't this also related to #4 ?
The way `NULL` is specified might fit in the iterator context like XML namespaces?

**Comment by pmaria** [comment]
Sort of, however, this seems to me like it makes more sense to be part of the `rml:Source`.

I think things that are inherently properties of the source itself should be placed there. So things like location, encoding, and how it specifies null (if there is no standard for it) should be placed there.

Now if we'd want to control and change the way the reference formulation interprets null values, then that property makes sense on the reference formulation.

**Comment by DylanVanAssche** [comment]
I only see `rml:source` as how the data source is accessed and how to retrieve the data in the source, without reading/processing it. This allows us to use any kind of ontology here so the spec is open here for the future.

However, we could introduce a `rml:Source` which looks like this:

```
rml:source [
  rml:access [
    # what we had previously for `rml:source` is now here
    # location & access (ex: WoT has security and location here)
  ];
  rml:encoding enc:UTF-8;
  rml:null "THIS IS A NULL VALUE";
]
```

Something else I just thought of: compression. Some datasets are provided as a ZIP or something, made a separate issue for that: #9

**Comment by pmaria** [comment]
Yes I like that idea for the `rml:Source`!

**Comment by andimou** [comment]
devil's advocate here but if we want to define different behaviours per column/object/element? now whatever we overwrite is universal, right?

**Comment by DylanVanAssche** [comment]
> devil's advocate here but if we want to define different behaviours per column/object/element? now whatever we overwrite is universal, right?

True, you set it for the data source. In *most* cases, the NULL value is defined for a complete data source.
However, you can do this more fine-grained by just making multiple Logical Sources if you need it.

**Comment by DylanVanAssche** [comment]
> but in one Triples Map I can only have 1 LS, no? what if I want to generate a Literal based on a template and use two different columns that I want them to have different behaviours?! (still devile's advocate here :) )

That's a hard problem, but such a behavior goes out-of-scope for this IMO.
To have such specialized behavior, you can use an FnO function.

**Comment by andimou** [comment]
and why this is out-of-scope?! in that sense, you could also change the default of every possible case with a function, where do you draw the line? why is the template out of scope and the reference is in scope?

**Comment by andimou** [comment]
> Another option here is to not specify rml:null in rml:Source, but in rml:ReferenceFormulation as discussed https://github.com/kg-construct/rml-target-source-spec/issues/4 .

While I fully agree about #4, I'm not sure if that would work here as well. But it might make sense to leave it per data source here and for more fine grained options, one should consider the use of fields indeed.

**Comment by DylanVanAssche** [comment]
> While I fully agree about https://github.com/kg-construct/rml-target-source-spec/issues/4, I'm not sure if that would work here as well. But it might make sense to leave it per data source here and for more fine grained options, one should consider the use of fields indeed.

I think that's a good compromise. The different extensions we propose in the KGC are each time more fine-grained:

Level 0: Core + RML/FNO spec: basic mapping 
Level 1: Core + RML/FNO spec + this spec: basic mapping + source access and target export
Level 2: Core + RML/FNO spec + this spec + fields/containers/collection: more mapping + all of the above.
Level 3: ...

So if you only need Level 1 functionality, you only implement specs from level 0 until 1.
Levels are here just mentioned for the text, in reality, we don't have these levels or a definition which specs are related to a level.
