### ISSUE TITLE
Paginated sources

### ISSUE THREAD

**Issue by DylanVanAssche** [kg-construct/rml-target-source-spec#8]
Paginated JSON/XML/... is used extensively in the wild for Web APIs.
However, we don't support this in the current Logical Source.

See:
- https://github.com/RMLio/rmlmapper-java/issues/155
- https://github.com/RMLio/yarrrml-parser/issues/156

**Comment by JBPressac** [comment]
Thank you !

**Comment by dachafra** [comment]
is this relevant for RML? Do we want to include it in the spec? I mean, databases also include pagination (`offset + limit`) but we do not include it in the spec as IMO it is more related to the capabilities of the underlying source than the actual access to the data

**Comment by DylanVanAssche** [comment]
@dachafra Pagination may be 'easier' in relational databases, but in Web APIs this is a huge mess as everyone does this differently. If you want to map Web APIs, this is a big requirement to have some adoption.

Most of the time (at least what I have seen, every time), the response contains a link or a next page number number to the next page. Logical Sources should have some way of declaring how a next page URL can be generated. If a Logical Source knows that, it can handle everything in the implementation.

IMO, this is an access problem so it would be description like WoT/D2RQ/CSVW/... which specifies the next page URL in some way. So this would end up in the Source, not in the Logical Source.

**Comment by andimou** [comment]
we need to distinguish between API pagination and JSON as pagination might be more relevant for the source description whereas if it's JSON or other format it is more a concern of the logical source. 

Then question would be, are there well-known (ideallly W3C recommended) vocabularies that describe pagination where we could point to if we want to suggest options to describe paginated data sources?

We should not forget that in the RML spec we don't want to be complete with respect to all potential data source descriptions. We can conclude on recommending a few and provide the means for people to include any data source they like (in that case paginated data sources) but we should not aim to be exhaustive (I think)

**Comment by JBPressac** [comment]
Hello,
There is a pagination example in the JSON:API specification: https://jsonapi.org/examples/#pagination and [a profile](https://jsonapi.org/profiles/ethanresnick/cursor-pagination/) to avoid many of the pitfalls of “offset–limit” pagination. But this could be unknown by some (most ?) API programmers.

**Comment by DylanVanAssche** [comment]
> Then question would be, are there well-known (ideallly W3C recommended) vocabularies that describe pagination where we could point to if we want to suggest options to describe paginated data sources?

- Hydra has a `pageNext` or `pagePrevious`: https://www.hydra-cg.com/spec/latest/core/. Hydra is a W3C CG.
- TREE does also some pagination across trees: https://tree.linkeddatafragments.org/spec. However, this is in its early stages and not a W3C thing.

I'm not aware of any other approaches for this, if anyone knows any, please comment ;)

> We should not forget that in the RML spec we don't want to be complete with respect to all potential data source descriptions. We can conclude on recommending a few and provide the means for people to include any data source they like (in that case paginated data sources) but we should not aim to be exhaustive (I think)

Indeed, we cannot cover everything. However, paginated sources are really common, could be seen as a batch stream with instructions on how to get the next batch. If we have a proper description on how to get the next batch, all the stuff is covered.

**Comment by DylanVanAssche** [comment]
This will be solved together with #18

**Comment by DylanVanAssche** [comment]
Implemented in f773d4b
