### ISSUE TITLE
Compressed sources

### ISSUE THREAD

**Issue by DylanVanAssche** [kg-construct/rml-target-source-spec#9]
Compressed sources, do we want to handle this like this:

```
rml:source [
  rml:access [
    # what we had previously for `rml:source` is now here
    # location & access (ex: WoT has security and location here)
  ];
  rml:encoding enc:UTF-8;
  rml:null "THIS IS A NULL VALUE";
  rml:compression comp:Zip;
]
```

Or do we need to handle this as nested Logical Sources? This approach won't work for a ZIP file with multiple files.

**Comment by dachafra** [comment]
Not a vocabulary, but a possibility could be to use the MIME types: https://docs.w3cub.com/http/basics_of_http/mime_types/complete_list_of_mime_types.html

**Comment by bjdmeest** [comment]
Nested logical sources could also prove to be beneficial for, e.g. "an RDB table where one column is a JSON object", so maybe it makes sense to investigate this on a higher level? (I couldn't find an active challenge on that though)
